version: "3.8"

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=lpcpwd_db
      - DB_PORT=3306
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_TOKEN_EXP=15m
      - REFRESH_TOKEN_EXP=7d
    depends_on:
      - db
      # - redis

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: lpcpwd_db
    ports:
      - "3306:3306"

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
